'use strict';
if(!document.querySelector('script[src$="analytics.js"]')){const s=document.createElement('script');s.src='analytics.js';s.defer=true;document.head.appendChild(s)}
const APPLIANCES=[['LED light',10],['Ceiling fan',75],['Standing fan',55],['Television',100],['Wi-Fi router',15],['Laptop',65],['Desktop computer',250],['Fridge',200],['Freezer',350],['Decoder',25],['Phone charger',10],['Water pump',1100],['Air conditioner 1HP',1000],['Air conditioner 1.5HP',1500],['Microwave',1200],['Electric iron',1200],['Washing machine',500],['CCTV system',80],['Other',100]];
const SURGE_LOADS=/pump|conditioner|fridge|freezer|compressor|washing machine/i;
const DEFAULT_PRICE_TIERS=[{max:500,label:'500W Essential Backup',price:'Diagnosis required'},{max:800,label:'800W Comfort Backup',price:'Diagnosis required'},{max:1000,label:'1kW Home Basic',price:'Diagnosis required'},{max:1500,label:'1.5kW Home Essential',price:'Diagnosis required'},{max:2000,label:'2kW Home Plus',price:'Diagnosis required'},{max:3000,label:'3kW Starter Power',price:'From GHS 15,000+'},{max:5000,label:'5kW Smart Home',price:'From GHS 25,000+'},{max:8000,label:'8kW Business Power',price:'From GHS 45,000+'},{max:Number.MAX_SAFE_INTEGER,label:'Industrial Custom Design',price:'Custom quote'}];
const ASSUMPTIONS={inverterEfficiency:.9,usableDepth:.8,energyMargin:1.25,solarHours:4.5};let PRICE_TIERS=DEFAULT_PRICE_TIERS,currentEstimate=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],table=$('#loadTable');
function loadPriceBook(){const endpoint=window.HOVER_CONFIG?.appsScriptUrl;if(!endpoint)return;const callback='hoverPriceBookCallback_'+Date.now(),script=document.createElement('script');let done=false;const cleanup=()=>{if(done)return;done=true;clearTimeout(timer);delete window[callback];script.remove()};window[callback]=payload=>{try{if(payload?.ok&&Array.isArray(payload.tiers)){const tiers=payload.tiers.map(t=>({max:Number(t.max),label:String(t.label||''),price:String(t.price||'Diagnosis required')})).filter(t=>Number.isFinite(t.max)&&t.max>0&&t.label).sort((a,b)=>a.max-b.max);if(tiers.length){PRICE_TIERS=tiers;calculate()}}}finally{cleanup()}};script.src=`${endpoint}${endpoint.includes('?')?'&':'?'}action=priceBook&callback=${encodeURIComponent(callback)}`;script.onerror=cleanup;const timer=setTimeout(cleanup,8000);document.head.appendChild(script)}
function options(selected=''){return APPLIANCES.map(([name,watts])=>`<option value="${watts}" ${name===selected?'selected':''}>${name}</option>`).join('')}
function addRow(name='Other',qty=1,hours=4){const watts=APPLIANCES.find(a=>a[0]===name)?.[1]||100,row=document.createElement('div');row.className='load-row';row.innerHTML=`<label><span>Appliance</span><select class="appliance" aria-label="Appliance">${options(name)}</select></label><label><span>Watts</span><input class="watts" type="number" min="1" max="50000" inputmode="decimal" value="${watts}" aria-label="Watts"></label><label><span>Quantity</span><input class="qty" type="number" min="1" max="99" inputmode="numeric" value="${qty}" aria-label="Quantity"></label><label><span>Hours/day</span><input class="hours" type="number" min="0" max="24" step="0.5" inputmode="decimal" value="${hours}" aria-label="Hours per day"></label><button type="button" class="remove" aria-label="Remove ${name}">×</button>`;table.appendChild(row);const select=row.querySelector('.appliance');select.addEventListener('change',()=>{row.querySelector('.watts').value=select.value;row.querySelector('.remove').setAttribute('aria-label',`Remove ${select.selectedOptions[0].text}`);calculate()});row.querySelectorAll('input').forEach(i=>i.addEventListener('input',calculate));row.querySelector('.remove').addEventListener('click',()=>{row.remove();calculate();if(!table.querySelector('.load-row'))$('#addLoad').focus()});calculate()}
function getSchedule(){return $$('.load-row').map(r=>{const name=r.querySelector('.appliance').selectedOptions[0].text,watts=Math.max(0,+r.querySelector('.watts').value||0),quantity=Math.max(0,+r.querySelector('.qty').value||0),hours=Math.min(24,Math.max(0,+r.querySelector('.hours').value||0));return{name,watts,quantity,hours,connectedWatts:watts*quantity,energyWh:watts*quantity*hours}})}
function summaryText(e){return `Hover Consult planning estimate\nConnected load: ${e.load.toLocaleString()} W\nDaily energy: ${e.energyKwh.toFixed(2)} kWh\nDesign load with growth/surge allowance: ${e.designLoad.toLocaleString()} W\nSuggested inverter class: ${e.system}\nBackup target: ${e.backup} hours\nIndicative usable storage: ${e.usableBatteryKwh.toFixed(1)} kWh (${e.batteryKwh.toFixed(1)} kWh nominal at 80% usable depth)\nIndicative solar array: ${e.pvKwp.toFixed(1)} kWp\nPlanning price: ${e.price}\nAssumptions: entered daily runtime, 90% inverter efficiency, 80% usable battery depth and 25% energy margin.\nThis is a mathematical planning estimate, not a final engineering recommendation or quotation.`}
function calculate(){const schedule=getSchedule(),load=schedule.reduce((n,x)=>n+x.connectedWatts,0),energyWh=schedule.reduce((n,x)=>n+x.energyWh,0),growth=+$('#growth').value,backup=+$('#backupHours').value,hasSurge=schedule.some(x=>x.connectedWatts&&SURGE_LOADS.test(x.name)),surgeFactor=hasSurge?1.25:1,designLoad=Math.ceil(load*growth*surgeFactor),tier=PRICE_TIERS.find(t=>designLoad<=t.max)||PRICE_TIERS.at(-1),dailyKwh=energyWh/1000,backupEnergyKwh=dailyKwh*Math.min(backup/24,1),usableBatteryKwh=load?backupEnergyKwh/ASSUMPTIONS.inverterEfficiency*ASSUMPTIONS.energyMargin:0,batteryKwh=usableBatteryKwh/ASSUMPTIONS.usableDepth,pvKwp=dailyKwh?dailyKwh/ASSUMPTIONS.solarHours*ASSUMPTIONS.energyMargin/ASSUMPTIONS.inverterEfficiency:0;
  $('#totalWatts').textContent=`${load.toLocaleString()} W`;$('#dailyEnergy').textContent=`${dailyKwh.toFixed(2)} kWh`;$('#systemClass').textContent=load?tier.label:'Add appliances';$('#batteryGuide').textContent=load?`${usableBatteryKwh.toFixed(1)} kWh`:'0 kWh';$('#solarGuide').textContent=load?`${pvKwp.toFixed(1)} kWp`:'0 kWp';$('#backupResult').textContent=`${backup} hours`;$('#priceGuide').textContent=load?tier.price:'Diagnosis required';$('#estimateTitle').textContent=load?tier.label:'Build your load profile';
  const explanation=load?`Your entered schedule uses ${dailyKwh.toFixed(2)} kWh per day. For a ${backup}-hour planning window, the estimate allows ${usableBatteryKwh.toFixed(1)} kWh of usable storage and approximately ${pvKwp.toFixed(1)} kWp of solar. ${hasSurge?'A 25% starting-load caution has been added because the profile includes a motor or compressor. ':''}Final selection still requires technical validation.`:'Your preliminary estimate will appear here. A technical review is still required.';$('#estimateText').textContent=explanation;
  currentEstimate=load?{load,energyKwh:+dailyKwh.toFixed(2),designLoad,backup,growthAllowance:Math.round((growth-1)*100),inverterEfficiency:ASSUMPTIONS.inverterEfficiency,usableDepth:ASSUMPTIONS.usableDepth,usableBatteryKwh:+usableBatteryKwh.toFixed(1),batteryKwh:+batteryKwh.toFixed(1),pvKwp:+pvKwp.toFixed(1),surgeReviewRequired:hasSurge,system:tier.label,price:tier.price,items:schedule.map(x=>`${x.name} ×${x.quantity} (${x.watts}W, ${x.hours}h/day)`).join('; ')}:null;const estimateInput=$('#estimateField');if(estimateInput)estimateInput.value=currentEstimate?JSON.stringify(currentEstimate):'';
  const enabled=Boolean(load),use=$('#useEstimate'),copy=$('#copyEstimate'),print=$('#printEstimate'),wa=$('#whatsappEstimate');[use,copy,print].forEach(x=>x.disabled=!enabled);wa.classList.toggle('disabled',!enabled);wa.setAttribute('aria-disabled',String(!enabled));wa.href=enabled?`https://wa.me/${window.HOVER_CONFIG?.whatsappNumber||'233244358113'}?text=${encodeURIComponent('Hello Hover Consult, please review this estimate:\n\n'+summaryText(currentEstimate))}`:'#'}
function selectRequest(service){$('#serviceSelect').value=service;$('#request').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});setTimeout(()=>$('#requestForm [name="name"]').focus(),400)}
function closeMenu(){const nav=$('#primaryNav'),toggle=$('.menu-toggle');nav.classList.remove('open');toggle.setAttribute('aria-expanded','false');toggle.querySelector('.menu-label').textContent='Menu';document.body.classList.remove('menu-open');$('#siteHeader').classList.remove('menu-active')}
$('.menu-toggle').addEventListener('click',e=>{const open=!$('#primaryNav').classList.contains('open');$('#primaryNav').classList.toggle('open',open);e.currentTarget.setAttribute('aria-expanded',String(open));e.currentTarget.querySelector('.menu-label').textContent=open?'Close':'Menu';document.body.classList.toggle('menu-open',open);$('#siteHeader').classList.toggle('menu-active',open)});$$('#primaryNav a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});addEventListener('scroll',()=>$('#siteHeader').classList.toggle('scrolled',scrollY>16),{passive:true});addEventListener('resize',()=>{if(innerWidth>820)closeMenu()});
$('#addLoad').addEventListener('click',()=>addRow());$('#growth').addEventListener('change',calculate);$('#backupHours').addEventListener('change',calculate);$$('[data-request]').forEach(b=>b.addEventListener('click',()=>selectRequest(b.dataset.request)));$('#useEstimate').addEventListener('click',()=>selectRequest('Energy requirement review'));$('#copyEstimate').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(summaryText(currentEstimate));$('#copyStatus').textContent='Estimate copied to your clipboard.'}catch(_){$('#copyStatus').textContent='Copy was unavailable. Use Print to save the summary.'}});$('#printEstimate').addEventListener('click',()=>print());
addRow('LED light',6,6);addRow('Television',1,5);addRow('Wi-Fi router',1,12);addRow('Fridge',1,12);
$('#requestForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,status=$('#formStatus'),button=form.querySelector('[type="submit"]');if(button.disabled)return;if(!form.checkValidity()){form.reportValidity();status.className='form-status error';status.textContent='Please complete the highlighted required fields.';return}const data=Object.fromEntries(new FormData(form));if(currentEstimate)data.estimate=JSON.stringify(currentEstimate);if(data.website)return;data.source='Hover Consult Energy Platform';data.submittedAt=new Date().toISOString();button.disabled=true;button.textContent='Sending request…';status.className='form-status working';status.textContent='Securely sending your request…';const endpoint=window.HOVER_CONFIG?.appsScriptUrl;if(!endpoint){status.className='form-status setup';status.innerHTML='Online submission is temporarily unavailable. Please continue on WhatsApp or call <a href="tel:+233244358113">+233 24 435 8113</a>.';button.disabled=false;button.textContent='Send request for technical review';return}try{await fetch(endpoint,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(data)});status.className='form-status success';status.textContent='Request sent. Hover Consult will review it and respond using your contact details.';form.reset();const estimateInput=$('#estimateField');if(estimateInput)estimateInput.value=currentEstimate?JSON.stringify(currentEstimate):''}catch(_){status.className='form-status error';status.innerHTML='We could not confirm the submission. Please <a href="tel:+233244358113">call</a> or use WhatsApp.'}finally{button.disabled=false;button.textContent='Send request for technical review'}});
$('#year').textContent=new Date().getFullYear();if('IntersectionObserver'in window&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const observer=new IntersectionObserver(entries=>entries.forEach(x=>{if(x.isIntersecting){x.target.classList.add('visible');observer.unobserve(x.target)}}),{threshold:.08});$$('.reveal').forEach(x=>observer.observe(x))}else $$('.reveal').forEach(x=>x.classList.add('visible'));loadPriceBook();
