const CONFIG=window.HOVER_CONFIG||{};document.querySelectorAll('.year').forEach(x=>x.textContent=new Date().getFullYear());const menu=document.querySelector('.menu');if(menu)menu.addEventListener('click',()=>{const nav=document.querySelector('.header nav'),open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.textContent=open?'Close':'Menu'});
if(location.pathname.endsWith('clinic.html'))location.replace('clinic/');
if(!document.querySelector('script[src$="analytics.js"]')){const analyticsScript=document.createElement('script');analyticsScript.src='analytics.js';document.head.appendChild(analyticsScript)}
document.querySelectorAll('.channel-links a').forEach(link=>link.style.color='#102131');
const MAX_FILE=4*1024*1024;
function setStatus(id,text,type='info'){const box=document.getElementById(id);if(!box)return;box.className=`status-box show ${type}`;box.innerHTML=text}
async function filePayload(input){const file=input?.files?.[0];if(!file)return null;if(file.size>MAX_FILE)throw new Error(`${file.name} exceeds the 4 MB limit.`);const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file)});return{name:file.name,mimeType:file.type||'application/octet-stream',size:file.size,data}}
async function sendPayload(payload){if(!CONFIG.appsScriptUrl)throw new Error('SETUP_REQUIRED');await fetch(CONFIG.appsScriptUrl,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)});return true}
function formDataObject(form){const data=Object.fromEntries(new FormData(form));const a=window.HoverAnalytics?.attribution||{};return{...data,attribution:a,source:a.source||data.source||'',medium:a.medium||'',campaign:a.campaign||'',articleId:a.articleId||'',articleTitle:a.articleTitle||'',landingPage:a.landingPage||location.href,referringPage:a.referringPage||document.referrer||'',firstVisit:a.firstVisit||''}}
function setupRequired(id){setStatus(id,'Online submission is temporarily unavailable. Please email hoverconsult@gmail.com or call +233 24 435 8113.','warn')}
function escapeHtml(value=''){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function safeUrl(value=''){try{const u=new URL(value,location.href);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return''}}

const clinicForm=document.getElementById('clinicForm');if(clinicForm)clinicForm.addEventListener('submit',async e=>{e.preventDefault();const button=clinicForm.querySelector('[type=submit]');button.disabled=true;setStatus('clinicFormStatus','Preparing your files…');try{const data=formDataObject(clinicForm);if(data.website)return;data.requestType='clinicSubmission';data.image=await filePayload(document.getElementById('clinicImage'));data.document=await filePayload(document.getElementById('clinicDocument'));delete data.imageFile;delete data.documentFile;await sendPayload(data);setStatus('clinicFormStatus','Submission received for moderation. It will appear publicly only after Hover Consult approves it.','success');clinicForm.reset()}catch(err){err.message==='SETUP_REQUIRED'?setupRequired('clinicFormStatus'):setStatus('clinicFormStatus',escapeHtml(err.message),'error')}finally{button.disabled=false}});

function jsonp(url){return new Promise((resolve,reject)=>{const cb='hoverClinic_'+Date.now()+'_'+Math.random().toString(36).slice(2);const script=document.createElement('script');const timer=setTimeout(()=>{cleanup();reject(new Error('Feed request timed out'))},10000);function cleanup(){clearTimeout(timer);delete window[cb];script.remove()}window[cb]=data=>{cleanup();resolve(data)};script.onerror=()=>{cleanup();reject(new Error('Feed request failed'))};script.src=`${url}${url.includes('?')?'&':'?'}action=clinicFeed&callback=${cb}`;document.head.appendChild(script)})}
function shareLinks(post){const page=`${location.origin}${location.pathname}#post-${encodeURIComponent(post.id)}`,text=encodeURIComponent(post.title);return`<a class="share-link" target="_blank" rel="noopener" href="https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(page)}">Share on Facebook</a><a class="share-link" target="_blank" rel="noopener" href="https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(page)}">Share on LinkedIn</a><a class="share-link" href="mailto:?subject=${text}&body=${encodeURIComponent(page)}">Email</a>`}
function renderPost(post){const image=safeUrl(post.imageUrl)?`<img class="clinic-media" src="${escapeHtml(post.imageUrl)}" alt="">`:'';const doc=safeUrl(post.documentPreviewUrl)?`<div class="doc-reader"><h3>Read attached document</h3><iframe loading="lazy" src="${escapeHtml(post.documentPreviewUrl)}" title="${escapeHtml(post.title)} document"></iframe></div>`:'';const comments=(post.comments||[]).map(c=>`<div class="comment"><strong>${escapeHtml(c.name)}</strong><p>${escapeHtml(c.comment)}</p><small>${escapeHtml(c.date)}</small></div>`).join('')||'<p class="file-note">No approved comments yet.</p>';return`<article class="clinic-post" id="post-${escapeHtml(post.id)}">${image}<div class="clinic-body"><div class="clinic-meta"><span>${escapeHtml(post.category)}</span><span>${escapeHtml(post.date)}</span><span>By ${escapeHtml(post.author)}</span></div><h2>${escapeHtml(post.title)}</h2><p><strong>${escapeHtml(post.summary)}</strong></p><p>${escapeHtml(post.body).replace(/\n/g,'<br>')}</p><div class="clinic-actions">${shareLinks(post)}</div></div>${doc}<div class="comments"><h3>Public discussion</h3>${comments}<form class="inline-comment" data-post="${escapeHtml(post.id)}"><label>Your name<input name="name" autocomplete="name" required></label><label>Email (not public)<input name="email" type="email" autocomplete="email" required></label><label>Comment or question<textarea name="comment" rows="3" required maxlength="1200" placeholder="Add a respectful comment or practical question"></textarea></label><input name="website" class="honeypot" tabindex="-1"><button class="btn primary" type="submit">Send comment for review →</button><div class="status-box" role="status"></div></form></div></article>`}
async function loadClinic(){const feed=document.getElementById('clinicFeed'),status=document.getElementById('clinicStatus');if(!feed)return;if(!CONFIG.appsScriptUrl){status.className='empty-feed';status.innerHTML='<strong>Community posts are temporarily unavailable.</strong><br>You can still explore the published guides in the Clinic knowledge base.';return}try{const result=await jsonp(CONFIG.appsScriptUrl);const posts=result.posts||[];status.remove();feed.innerHTML=posts.length?posts.map(renderPost).join(''):'<div class="empty-feed">No published community posts yet.</div>';feed.querySelectorAll('.inline-comment').forEach(form=>form.addEventListener('submit',submitComment))}catch(err){status.className='empty-feed';status.textContent='The Clinic feed could not be loaded. Please try again later.'}}
async function submitComment(e){e.preventDefault();const form=e.currentTarget,box=form.querySelector('.status-box'),button=form.querySelector('button');button.disabled=true;box.className='status-box show info';box.textContent='Submitting for moderation…';try{const data=formDataObject(form);if(data.website)return;data.requestType='clinicComment';data.postId=form.dataset.post;await sendPayload(data);box.className='status-box show success';box.textContent='Comment received. It will join the public thread after moderation.';form.reset()}catch(err){box.className='status-box show error';box.textContent=err.message==='SETUP_REQUIRED'?'The publishing backend is not configured.':err.message}finally{button.disabled=false}}loadClinic();

const quoteFile=document.getElementById('quoteFile');if(quoteFile)quoteFile.addEventListener('change',()=>{const file=quoteFile.files[0],preview=document.getElementById('quotePreview');if(!file){preview.className='viewer-empty';preview.textContent='Choose a PDF or image to preview it here before submission.';return}if(file.size>MAX_FILE){preview.className='viewer-empty';preview.textContent='This file exceeds the 4 MB limit.';return}const url=URL.createObjectURL(file);preview.className='';preview.innerHTML=file.type.startsWith('image/')?`<img src="${url}" alt="Quotation preview" style="max-width:100%;display:block;margin:auto">`:`<iframe src="${url}" title="Quotation preview"></iframe>`});
const quoteForm=document.getElementById('quoteVerifyForm');if(quoteForm){const service=CONFIG.paymentServices?.quoteVerification;if(service){const payment=document.createElement('div');payment.className='moderation-note';payment.innerHTML=`<strong>Independent quotation verification — ${escapeHtml(service.fee)}</strong><br><a class="service-link" href="${service.url}" target="_blank" rel="noopener">Pay securely with Paystack →</a><br><small>After payment, enter the transaction reference below and submit your quotation.</small>`;quoteForm.prepend(payment);const reference=document.createElement('label');reference.innerHTML='Payment reference<input name="paymentReference" required placeholder="Paystack transaction/reference number">';payment.after(reference)}quoteForm.addEventListener('submit',async e=>{e.preventDefault();const button=quoteForm.querySelector('[type=submit]');button.disabled=true;setStatus('quoteStatus','Preparing your private documents…');try{const data=formDataObject(quoteForm);if(data.website)return;data.requestType='quoteVerification';data.paymentService=service?.label||'Quote verification';data.paymentFee=service?.fee||'GHS 200';data.quoteFile=await filePayload(document.getElementById('quoteFile'));data.quoteImage=await filePayload(document.getElementById('quoteImage'));await sendPayload(data);setStatus('quoteStatus','Quotation submitted. A reference and acknowledgement will be sent by email.','success');quoteForm.reset();document.getElementById('quotePreview').className='viewer-empty';document.getElementById('quotePreview').textContent='Quotation submitted for private review.'}catch(err){err.message==='SETUP_REQUIRED'?setupRequired('quoteStatus'):setStatus('quoteStatus',escapeHtml(err.message),'error')}finally{button.disabled=false}})}

const paymentButton=document.getElementById('paymentButton');let selectedPaymentService=null;if(paymentButton){const services=CONFIG.paymentServices||{},feeText=document.getElementById('feeText'),card=paymentButton.closest('.payment-card'),select=document.createElement('select');select.id='paymentService';select.className='payment-service';select.setAttribute('aria-label','Choose a paid advisory service');Object.entries(services).forEach(([key,item])=>select.add(new Option(`${item.label} — ${item.fee}`,key)));if(Object.keys(services).length){card.insertBefore(select,feeText);const updatePayment=()=>{selectedPaymentService=services[select.value];feeText.textContent=`Service fee: ${selectedPaymentService.fee}`;paymentButton.href=selectedPaymentService.url;paymentButton.classList.remove('disabled');paymentButton.removeAttribute('aria-disabled');paymentButton.target='_blank';paymentButton.rel='noopener';paymentButton.textContent='Pay securely with Paystack →';document.getElementById('paymentSetup').textContent='After payment, return to this page with your transaction reference or screenshot.'};select.addEventListener('change',updatePayment);updatePayment()}else if(CONFIG.paymentUrl){feeText.textContent=`Consultation fee: ${CONFIG.consultationFee}`;paymentButton.href=CONFIG.paymentUrl;paymentButton.classList.remove('disabled');paymentButton.removeAttribute('aria-disabled');paymentButton.target='_blank';paymentButton.rel='noopener'}else paymentButton.addEventListener('click',e=>e.preventDefault())}
const bookingForm=document.getElementById('bookingForm');if(bookingForm)bookingForm.addEventListener('submit',async e=>{e.preventDefault();const button=bookingForm.querySelector('[type=submit]');button.disabled=true;setStatus('bookingStatus','Preparing your reservation request…');try{const data=formDataObject(bookingForm);if(data.website)return;data.requestType='consultationBooking';data.paymentService=selectedPaymentService?.label||'Hourly consultation';data.paymentFee=selectedPaymentService?.fee||CONFIG.consultationFee;data.message=`Paid service: ${data.paymentService} (${data.paymentFee})\n\n${data.message}`;data.paymentProof=await filePayload(document.getElementById('paymentProof'));await sendPayload(data);setStatus('bookingStatus','Reservation received. Hover Consult will verify payment and confirm the available session by email or WhatsApp.','success');bookingForm.reset()}catch(err){err.message==='SETUP_REQUIRED'?setupRequired('bookingStatus'):setStatus('bookingStatus',escapeHtml(err.message),'error')}finally{button.disabled=false}});
