const SHOP_FALLBACK=[
{id:'HC-PV-001',category:'Solar Panels',name:'Solar PV modules',description:'Mono-crystalline module options for residential and commercial arrays.',specifications:'Final wattage, efficiency and warranty depend on the approved model.',priceLabel:'Price on request',stockStatus:'Available to order',imageUrl:'assets/panels/generated-solar-panel-v1.jpg',featured:true,rating:0,reviewCount:0,reviews:[]},
{id:'HC-INV-001',category:'Inverters',name:'Hybrid solar inverters',description:'Hybrid inverter options for backup, solar charging and grid coordination.',specifications:'Selected after continuous-load, surge, battery, phase and PV-input assessment.',priceLabel:'Price on request',stockStatus:'Configured to order',imageUrl:'assets/panels/generated-hybrid-inverter-v1.jpg',featured:true,rating:0,reviewCount:0,reviews:[]},
{id:'HC-BAT-001',category:'Batteries',name:'Lithium energy storage',description:'Modular storage options for home, business and institutional backup.',specifications:'Usable energy, charge rate and compatibility are validated during design.',priceLabel:'Price on request',stockStatus:'Configured to order',imageUrl:'assets/panels/generated-lithium-battery-v1.jpg',featured:true,rating:0,reviewCount:0,reviews:[]},
{id:'HC-PRO-001',category:'Protection',name:'Solar protection and control package',description:'Coordinated DC and AC protection, isolation, earthing and circuit control.',specifications:'Final equipment follows the approved single-line design and site conditions.',priceLabel:'Price on request',stockStatus:'Designed per project',imageUrl:'assets/panels/generated-protection-package-v1.jpg',featured:false,rating:0,reviewCount:0,reviews:[]},
{id:'HC-PMP-001',category:'Productive Use',name:'Solar water-pumping package',description:'Solar pumping architecture for boreholes, farms and water-storage systems.',specifications:'Pump duty, total dynamic head, daily water volume and controls require assessment.',priceLabel:'Price on request',stockStatus:'Designed per project',imageUrl:'assets/panels/generated-solar-pump-v1.jpg',featured:false,rating:0,reviewCount:0,reviews:[]},
{id:'HC-VFD-001',category:'Motor Control',name:'Variable-frequency drive (VFD)',description:'Motor-speed control for pumps, fans and productive-use systems, including solar pumping applications.',specifications:'Motor nameplate current, voltage, phase, duty, enclosure, control method and cable length must be verified before selection.',priceLabel:'Price on request',stockStatus:'Configured to order',imageUrl:'assets/panels/vfd-3.jpg',featured:true,rating:0,reviewCount:0,reviews:[]}
];
let products=[];const grid=document.getElementById('productGrid'),search=document.getElementById('productSearch'),category=document.getElementById('productCategory'),reviewProduct=document.getElementById('reviewProduct');
function escapeShop(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderShop(){const q=search.value.toLowerCase(),cat=category.value,list=products.filter(p=>(!cat||p.category===cat)&&(!q||`${p.name} ${p.category} ${p.description} ${p.brand||''} ${p.model||''}`.toLowerCase().includes(q)));grid.innerHTML=list.length?list.map(p=>`<article class="product-card"><div class="product-visual">${p.imageUrl?`<img src="${escapeShop(p.imageUrl)}" alt="${escapeShop(p.name)}">`:escapeShop(p.category)}</div><div class="product-card-content"><div class="product-meta"><span>${escapeShop(p.category)}</span><span>${escapeShop(p.stockStatus||'Confirm availability')}</span></div><h3>${escapeShop(p.name)}</h3><p>${escapeShop(p.description)}</p><p class="product-spec"><strong>Selection note:</strong> ${escapeShop(p.specifications)}</p>${p.reviewCount?`<div class="rating">★ ${p.rating} from ${p.reviewCount} approved review${p.reviewCount===1?'':'s'}</div>`:'<div class="rating">No approved reviews yet</div>'}<div class="product-price"><strong>${escapeShop(p.price?`GHS ${p.price}`:p.priceLabel||'Price on request')}</strong><a href="index.html#request">Request assessment →</a></div>${p.reviews?.length?`<div class="reviews-list">${p.reviews.slice(0,2).map(r=>`<blockquote><strong>${escapeShop(r.name)} · ${r.rating}/5</strong><br>${escapeShop(r.review)}</blockquote>`).join('')}</div>`:''}</div></article>`).join(''):'<div class="empty-products">No products match this search.</div>'}
function setProducts(list){products=list?.length?list:SHOP_FALLBACK;document.getElementById('shopStatus').remove();[...new Set(products.map(p=>p.category))].sort().forEach(c=>category.insertAdjacentHTML('beforeend',`<option>${escapeShop(c)}</option>`));products.forEach(p=>reviewProduct.insertAdjacentHTML('beforeend',`<option value="${escapeShop(p.id)}">${escapeShop(p.name)}</option>`));renderShop()}
function loadProducts(){const endpoint=window.HOVER_CONFIG?.appsScriptUrl;if(!endpoint){setProducts(SHOP_FALLBACK);return}const cb='hoverCatalog_'+Date.now();window[cb]=data=>{delete window[cb];document.getElementById(cb)?.remove();setProducts(data.products)};const s=document.createElement('script');s.id=cb;s.src=`${endpoint}?action=catalog&callback=${cb}`;s.onerror=()=>setProducts(SHOP_FALLBACK);document.head.appendChild(s)}
search.addEventListener('input',renderShop);category.addEventListener('change',renderShop);document.getElementById('productReviewForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,box=document.getElementById('productReviewStatus'),button=form.querySelector('button');if(!window.HOVER_CONFIG?.appsScriptUrl){box.className='status-box show warn';box.textContent='Online reviews are temporarily unavailable. Please try again later.';return}button.disabled=true;box.className='status-box show info';box.textContent='Submitting your review…';try{const data=Object.fromEntries(new FormData(form));if(data.website)return;data.requestType='productReview';await fetch(window.HOVER_CONFIG.appsScriptUrl,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain'},body:JSON.stringify(data)});box.className='status-box show success';box.textContent='Thank you. Your review has been received for moderation.';form.reset()}catch{box.className='status-box show error';box.textContent='Your review could not be submitted. Please try again later.'}finally{button.disabled=false}});loadProducts();
